name: NodeJS with Webpack

on:
  push:
    branches: [ "build" ]
  pull_request:
    branches: [ "build" ]

jobs:
  build:
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Set up Python 2.7
      uses: actions/setup-python@v3
      with:
        python-version: '2.7'

    - name: Install
      run: npm install

    - name: Build
      run: npm run build
